const sample=require('../controllers/sample.controller')
const express=require('express')
const router=express.Router()
router.post('/addsample',sample.addSample)
router.put('/sendsample/:sampleId',sample.sendSample)
router.put('/finishsample/:sampleId',sample.finishSample)
router.delete('/deletesample/:sampleId',sample.deleteSample)
router.get('/all',sample.getAllSamples)
router.get('/getsample/:sampleId',sample.getSample)
router.get('/notsended',sample.getNotSendedSamples)
router.get('/notfinished',sample.getNotfinishedSamples)
router.get('/delayedsending?',sample.getdelayedSendedSamples)
router.get('/delayedfinishing?',sample.getdelayedFinishedSamples)
module.exports=router